Related renew
eccubevn/related-product-plugin pull request #1
Opened 2016-10-21 02:44 UTC by hoand-vn

for review corss

2016-10-21 02:46 UTC, hoand-vn commented on PluginManager.php
add description for class

2016-10-21 02:46 UTC, hoand-vn commented on PluginManager.php
> +    public function __construct()
can remove this function

2016-10-21 02:47 UTC, hoand-vn commented on PluginManager.php
add description for class

2016-10-21 02:49 UTC, hoand-vn commented on config.yml
> +version: 1.0.0
confirm version with Endo san : maybe 0.0.3

2016-10-21 03:08 UTC, hoand-vn commented on event.yml
>      - [addContentOnProductEdit, NORMAL]
function should be start with 'on' prefix

2016-10-21 03:13 UTC, hoand-vn commented on Controller/Admin/RelatedProductController.php
>  class RelatedProductController
add description for class

2016-10-21 03:13 UTC, hoand-vn commented on Controller/Admin/RelatedProductController.php
> +    public function searchProduct(Application $app, Request $request, $page_no = null)
change $page_no => Camel $pageNo

2016-10-21 03:17 UTC, hoand-vn commented on Controller/Admin/RelatedProductController.php
> +        return $app->render('RelatedProduct/Resource/template/admin/modal_result.twig', array(
commas for array

2016-10-21 03:23 UTC, hoand-vn commented on Form/Extension/Admin/RelatedCollectionExtension.php
>          return 'admin_product';
the closing brace of class Not need newline before

2016-10-21 03:25 UTC, hoand-vn commented on Form/Type/Admin/RelatedProductType.php
> +                    'placeholder' => $app->trans('plugin.related_product.type.comment.placeholder')),
add commas for each element of array

2016-10-21 03:27 UTC, hoand-vn commented on Resource/config/constant.yml
> +text_area_len: 4000
prefix name of plugin to avoid overwrite

2016-10-21 03:28 UTC, hoand-vn commented on Resource/config/path.yml
> +# urlpath
remove file path.yml if not use assets

2016-10-21 03:30 UTC, hoand-vn commented on Resource/doctrine/migration/Version20150808173000.php
> +            ))
indent remove

2016-10-21 03:36 UTC, hoand-vn commented on Service/RelatedProductService.php
>          );
add commas for each element of array

2016-10-21 03:36 UTC, hoand-vn commented on Service/RelatedProductService.php
>          return $unit[$this->unit];
add newline before return

2016-10-21 03:37 UTC, hoand-vn commented on Service/RelatedProductService.php
>          );
add commas for ele array

2016-10-24 01:59 UTC, ryo-endo commented on Controller/Admin/RelatedProductController.php
> +        $arrProduct = $pagination->getItems();
- [ ] unused $arrProduct

2016-10-24 02:01 UTC, ryo-endo commented
- [ ] please, apply php-cs-fixer.
> `php-cs-fixer --level=symfony fix .`

2016-10-24 02:05 UTC, ryo-endo commented
- [ ] did you solve ?  
https://github.com/EC-CUBE/related-product-plugin/issues/27

2016-10-24 02:08 UTC, ryo-endo commented
- [ ] add header comment for member variables. (for IDE code completion)  
please, check all files.

2016-10-24 02:09 UTC, lammn commented
Fixed 
https://github.com/EC-CUBE/related-product-plugin/issues/28
https://github.com/EC-CUBE/related-product-plugin/issues/16

2016-10-24 02:12 UTC, ryo-endo commented
- [ ] is upath.yml unused file ? if unused, please delete this file.

2016-10-24 02:27 UTC, ryo-endo commented
- [ ] 引数無しのflush()は使用しないでください。

2016-10-24 02:30 UTC, ryo-endo commented
- [ ] copyright の表記を統一してください。

2016-10-24 02:34 UTC, ryo-endo commented
- [ ] `'POST' == $request->getMethod()`を使用している箇所があります。新しい方式に修正してください。

2016-10-24 02:35 UTC, ryo-endo commented
Question
- [ ] why call 2 function on same event ?
```
eccube.event.route.admin_product_product_new.response:
    - [onProductEditRender, NORMAL]
    - [onProductEditRegister, NORMAL]
eccube.event.route.admin_product_product_edit.response:
    - [onProductEditRender, NORMAL]
    - [onProductEditRegister, NORMAL]
```

2016-10-24 02:36 UTC, ryo-endo commented on event.yml
> +#eccube.event.route.shopping.response:
unnecessary comment.

2016-10-24 02:37 UTC, ryo-endo commented on event.yml
> +    - [onProductEditRegister, NORMAL]
Question
- [ ] why call 2 function on same event ?
```
eccube.event.route.admin_product_product_new.response:
    - [onProductEditRender, NORMAL]
    - [onProductEditRegister, NORMAL]
eccube.event.route.admin_product_product_edit.response:
    - [onProductEditRender, NORMAL]
    - [onProductEditRegister, NORMAL]
```

2016-10-24 05:57 UTC, ryo-endo commented on Event.php
> +        $this->legacyEvent->addContentOnProductEdit($event);
新しいイベントでも、`legacyEvent`の関数を利用しています。
これでも動作はしますが、実装のお手本にならないので、修正をお願いします。

CategoryContentsプラグインを参考にしてください。
https://github.com/EC-CUBE/category-content-plugin

2016-10-24 05:57 UTC, ryo-endo commented on Event.php
> +        $this->legacyEvent->addContentOnProductEdit($event);
https://github.com/EC-CUBE/category-content-plugin/blob/master/CategoryContentEvent.php
カテゴリコンテンツでは、
onAdminProductCategoryIndexInit
onAdminProductCategoryIndexComplete
を使って処理を行っています。このような実装にしてください。

2016-10-24 05:57 UTC, ryo-endo commented on Event.php
> +        $this->legacyEvent->addContentOnProductEdit($event);
ただし、古いEC-CUBEでは、イベントを使用できないです。
EventLegacy.phpはいまの実装のままになってしまいますが仕方ありません。

2016-10-24 05:57 UTC, ryo-endo commented on Event.php
> +     */
- [ ] 旧フッポイントの関数コメントには、`@deprecated since v3.0.9, to be removed in 3.1.` を記載してください。
- [ ] この関数以外にも、旧フッポイントの関数コメントには追記お願いいます。

2016-10-24 06:25 UTC, ryo-endo commented
- [ ] `<!--# RelatedProductPlugin-Tag #--> ` の位置に差し込む対応をお願いします。

2016-10-24 06:59 UTC, lammn commented
# New hookpoint on version >= 3.0.9
eccube.event.route.admin_product_product_new.response:
    - [onRenderAdminProductEdit, NORMAL]
eccube.event.route.admin_product_product_edit.response:
    - [onRenderAdminProductEdit, NORMAL]
eccube.event.route.product_detail.response:
    - [onRenderProductDetail, NORMAL]

# deprecated event (for v3.0.0 - 3.0.8)
eccube.event.render.admin_product_product_new.before:
    - [OnRenderAdminProductEditBefore, NORMAL]
eccube.event.render.admin_product_product_edit.before:
    - [OnRenderAdminProductEditBefore, NORMAL]
eccube.event.render.product_detail.before:
    - [OnRenderProductDetailBefore, NORMAL]

2016-10-26 09:11 UTC, lqdung-lockon commented on Entity/RelatedProduct.php
> +     * @param $content
Need add param type.

2016-10-26 09:11 UTC, lqdung-lockon commented on Entity/RelatedProduct.php
> +     * @param Product
Need add param name.

2016-10-26 09:11 UTC, lqdung-lockon commented on Entity/RelatedProduct.php
> +     * @param $productId
Need add param type.

2016-10-26 09:11 UTC, lqdung-lockon commented on Entity/RelatedProduct.php
>      private $childProdcutId;
Naming is wrong!

2016-10-26 09:11 UTC, lqdung-lockon commented on Entity/RelatedProduct.php
> +     * @param $productId
Add param type.

2016-10-26 09:11 UTC, lqdung-lockon commented on Form/Extension/Admin/RelatedCollectionExtension.php
>      public function buildView(FormView $view, FormInterface $form, array $options)
Remove if don't use.

2016-10-26 09:11 UTC, lqdung-lockon commented on ServiceProvider/RelatedProductServiceProvider.php
>          }));
wrong comment. => // repository?

2016-10-26 09:11 UTC, lqdung-lockon commented on Tests/Web/RelatedProductAdminControllerTest.php
> +            $this->app->url('admin_product_product_new')
Opening parenthesis of a multi-line function call must be the last content on the line.

2016-10-26 09:11 UTC, lqdung-lockon commented on Tests/Web/RelatedProductAdminControllerTest.php
> +
Need add check redirect, success message, data in the layout after save.

2016-10-26 09:11 UTC, lqdung-lockon commented on Tests/Web/RelatedProductAdminControllerTest.php
> +
Need add check redirect, success message, data in the layout after save.

2016-10-26 09:11 UTC, lqdung-lockon commented on Tests/Web/RelatedProductAdminControllerTest.php
> +
Check the results returned are single.

2016-10-26 09:11 UTC, lqdung-lockon commented on Tests/Web/RelatedProductAdminControllerTest.php
> +
Check the results returned are single.

2016-10-26 09:11 UTC, lqdung-lockon commented on Tests/Web/RelatedProductAdminControllerTest.php
> +
Check the results returned are single.

2016-10-26 09:11 UTC, lqdung-lockon commented on Tests/Web/RelatedProductAdminControllerTest.php
> +
Check the results returned are single.

2016-10-26 09:11 UTC, lqdung-lockon commented on Tests/Web/RelatedProductAdminControllerTest.php
> +
Check the results returned are single.

2016-10-26 09:11 UTC, lqdung-lockon commented on Tests/Web/RelatedProductAdminControllerTest.php
> +
Check the results list.

2016-10-26 09:11 UTC, lqdung-lockon commented on Tests/Web/RelatedProductAdminControllerTest.php
> +}
- Add more test case for this requirement:
  設定をDBに保存する条件  
  商品      未選択   未選択   選択あり    選択あり
  説明文       未入力   入力あり    未入力   入力あり
  結果      保存しない 保存しない 保存する    保存する
- Litmit test (max RelatedProduct)
- Litmit above test (>max RelatedProduct).
- Add product invalid test. (id null, id do not exist,..)
- Max length of comment test.
- Product add without Related product.
- Remove product case.
- Add 2 related products are duplicate.
- Update 2 related products are duplicate.
- etc ...

2016-10-26 09:11 UTC, lqdung-lockon commented on Tests/Web/RelatedProductControllerTest.php
> +        $this->assertContains('関連商品', $crawler->html());
Check the name of the related product.

2016-10-26 09:11 UTC, lqdung-lockon commented on Tests/Web/RelatedProductControllerTest.php
> +}
- Add check over max related product.
- Check product private status.
- Product had deleted.

2016-10-26 09:11 UTC, lqdung-lockon commented on Event.php
> +        $replace = $snipet.$search;
Generally, Plugin Tag should above code.

2016-10-26 09:11 UTC, lqdung-lockon commented on Event.php
>          $loop = 5 - count($RelatedProducts);
Magic number: '5'. In this case, I think you should add constant.

2016-10-26 09:11 UTC, lqdung-lockon commented on Event.php
> +                ->setProductId($Product->getId())
If Product is null, You can't get product id => errors.
Implement this case to unit test.

2016-10-26 09:11 UTC, lqdung-lockon commented on EventLegacy.php
> +* This file is part of EC-CUBE
Copyright is wrong!!!

2016-10-26 09:11 UTC, lqdung-lockon commented on EventLegacy.php
> +            $loop = 5 - count($RelatedProducts);
Magic number... add constant or global variable.

2016-10-26 09:11 UTC, lqdung-lockon commented on PluginManager.php
Copyright is wrong.

2016-10-26 09:11 UTC, lqdung-lockon commented on PluginManager.php
> +    public function __construct()
remove if don't use.

2016-10-26 09:11 UTC, lqdung-lockon commented on PluginManager.php
> +     * @param $config
Add param type for all param.

2016-10-26 09:11 UTC, lqdung-lockon commented on event.yml
> +admin.product.edit.initialize:
Do you use this?

2016-10-26 09:11 UTC, lqdung-lockon commented on Event.php
> +    public function onRenderAdminProductInit(EventArgs $event)
Do you use this?

2016-10-27 04:01 UTC, ryo-endo commented
- [ ] FormExtensionを使わずに実装できないでしょうか？

2016-10-27 04:12 UTC, lammn commented
FormExtensionは必要だと思っています。

2016-10-27 04:25 UTC, ryo-endo commented
使わない場合どうなりますか？
「必要だと思っている」理由を教えてください。

2016-10-27 04:33 UTC, ryo-endo commented on event.yml
> -    - [onProductEditRegister, NORMAL]
これ削除して、大丈夫なのですか？

2016-10-27 04:33 UTC, ryo-endo commented on Event.php
> +        $loop = self::MAXIMUM_PRODUCT_RELATED - count($RelatedProducts);
- [x] if文の外で定義をお願いします

### detail

```
$RelatedProducts  = null;
if (xxx) {
   RelatedProducts = xxxxx;
}
$loop = self::MAXIMUM_PRODUCT_RELATED - count($RelatedProducts);
```

2016-10-27 04:33 UTC, ryo-endo commented on EventLegacy.php
> +     * @param Application\ $app
- [x] `Application\` -> `Application`

2016-10-27 04:33 UTC, ryo-endo commented on EventLegacy.php
> +     * @param $event
- [x] 変数の「型」を書いてください

2016-10-27 04:33 UTC, ryo-endo commented on EventLegacy.php
> +     * @return $Product
- [x] 戻り値の「型」を書いてください

2016-10-27 04:33 UTC, ryo-endo commented on Event.php
> +            $search = '{% if Product.freearea %}';
### [Bug]
- [ ] いまオーナーズストアに公開されている関連商品プラグインと、表示位置が変わりませんか？  
  互換性を気にしています。

2016-10-27 04:33 UTC, ryo-endo commented on Event.php
> +            $search = '{% if Product.freearea %}';
完全に互換性をキープするのは難しいと思いますが、できる限り近い場所に挿入してください。

2016-10-27 04:33 UTC, ryo-endo commented on Event.php
> +        $search = self::RELATED_PRODUCT_TAG;
- [x] 実装の意図の把握が難しいです。  
  以下のような実装にして、明示的に処理を分けてください。（何も知らない人が読んだときに迷わないように）  
  https://github.com/EC-CUBE/maker-plugin/commit/f9c1607aa488017fa22b3bb56e6683ec43cf9a3a

2016-10-27 04:33 UTC, ryo-endo commented on phpunit.xml.dist
> +         bootstrap="../../../tests/bootstrap.php"
- [x] maybe unnecessary. > bootstrap

2016-10-27 04:33 UTC, ryo-endo commented on phpunit.xml.dist
> +                <directory suffix=".php">./Resource</directory>
- [x] add ./Tests folder.

2016-10-27 04:33 UTC, ryo-endo commented on Event.php
> +        if ($form->isValid()) {
- [x] ProductController(イベント呼び出し側)でバリデーションOKだった場合にのみこのイベントが発生するので、イベント内でのバリデーションは不要です。

2016-10-27 04:33 UTC, ryo-endo commented on Event.php
>          if (!$app->isGranted('ROLE_ADMIN')) {
- [x] 新しいイベントではSymfonyFramework側で、権限チェックが完了しているので、ここでの`$app->isGranted('ROLE_ADMIN')`は不要です。

2016-10-27 04:33 UTC, ryo-endo commented on Event.php
> +        if (!$app->isGranted('ROLE_ADMIN')) {
- [x] 新しいイベントではSymfonyFramework側で、権限チェックが完了しているので、ここでの`$app->isGranted('ROLE_ADMIN')`は不要です。

2016-10-27 04:33 UTC, ryo-endo commented on Resource/template/admin/related_product.twig
> +<div class="box accordion">
### [Bug]
- [ ] タグが閉じられていません。

2016-10-27 04:33 UTC, ryo-endo commented on Entity/RelatedProduct.php
>      private $childProdcutId;
+1

2016-10-27 06:24 UTC, lammn commented on Resource/template/admin/related_product.twig
> +<div class="box accordion">
This is important div

2016-10-27 07:35 UTC, lqdung-lockon commented on Resource/template/admin/related_product.twig
> +<div class="box accordion">
Yes, you must close it at the end of file. If not, it will break the interface.

2016-10-27 11:12 UTC, ryo-endo commented on Entity/RelatedProduct.php
>      private $childProdcutId;
- [ ] 直ってないです。

2016-10-27 11:22 UTC, ryo-endo commented on config.yml
> +version: 1.0.0
1.0.0 <- ok

2016-10-31 06:53 UTC, ryo-endo commented
- [ ] postgreqlの場合、MetaDataからテーブルを生成すると、削除時にシーケンステーブル削除されないはず。

#### 参考
https://github.com/EC-CUBE/point-plugin/blob/master/Resource/doctrine/migration/Version20160428120000.php#L69
https://github.com/EC-CUBE/eccube-api/blob/master/Resource/doctrine/migrations/Version20160317161732.php#L86

2016-10-31 06:57 UTC, ryo-endo commented
https://github.com/eccubevn/related-product-plugin/blob/related-renew/Resource/template/front/related_product.twig#L19

- [ ] `|`の前後にスペース入れないようにしてください。OKの例:`{{ var|raw }}`
- [ ] `nl2br`必要ではないですか？
- [ ] 他のtwigファイルも確認お願いします。

2016-10-31 10:33 UTC, ryo-endo commented
- [ ] EC-CUBE本体のバージョン判定の処理を、Util関数としてまとめられないですか？

`if (version_compare(Constant::VERSION, '3.0.9', '<')) {`
`return version_compare('3.0.9', Constant::VERSION, '<=');`
`if (version_compare(Constant::VERSION, '3.0.9', '>=')) {`
みたいなところです。

2016-11-01 03:48 UTC, lqdung-lockon reviewed
Please check!

2016-11-01 03:48 UTC, lqdung-lockon commented on Event.php
> +        $parameters['form'] = $form;
Duplicate => remove this.

2016-11-01 03:48 UTC, lqdung-lockon commented on Event.php
> +        $parameters['searchForm'] = $searchForm;
Duplicate => remove this.

2016-11-01 03:48 UTC, lqdung-lockon commented on Event.php
> +        $parameters['Product'] = $Product;
Duplicate => remove this.

2016-11-01 03:48 UTC, lqdung-lockon commented on Event.php
> +        $form = $parameters['form'];
remove this.

2016-11-01 03:48 UTC, lqdung-lockon commented on Event.php
> +        $searchForm = $parameters['searchForm'];
remove this.

2016-11-01 03:55 UTC, ryo-endo requested changes

2016-11-01 03:55 UTC, ryo-endo commented on Resource/doctrine/migration/Version20150808173000.php
> +        if (Util::isSupportNewHookpoint()) {
- [ ] SupportNewHookpoint? maybe other reason.

2016-11-15 07:18 UTC, closed without merging

2016-12-06 06:30 UTC, ryo-endo commented on Event.php
> +                ->setProductId($Product->getId())
### Bug