Related product plugin renew
eccubevn/related-product-plugin pull request #3
Opened 2016-11-15 07:20 UTC by lammn

New pull request for plugin renew

2016-11-15 08:21 UTC, ryo-endo requested changes

2016-11-15 08:21 UTC, ryo-endo commented on ServiceProvider/RelatedProductServiceProvider.php
> +        if (!Util::isSupportNewHookpoint()) {
- [x] ここは`isSupportGetInstanceFunction`が適切ですね。  
  RecommendPluginと合わせておいてください。

2016-11-15 08:21 UTC, ryo-endo commented on Util/Util.php
> +class Util
- [x] 意味のある名前をお願いします。さすがにUtilは、ざっくりすぎる。  
  ⇒RecommendPluginと合わせて`Version`にしましょう。

2016-11-15 08:21 UTC, ryo-endo commented on Util/Util.php
> +        if (version_compare(Constant::VERSION, '3.0.9', '>=')) {
- [ ] コードの書き方を`isSupportLogFunction`と統一してください。

2016-11-15 08:21 UTC, ryo-endo commented on .travis.yml
> +  matrix:
- [ ] テスト対象をグルーピングしてみました。以下の３つでテストしませんか？  
3.0.0-3.0.8  ⇒ 3.0.8  
3.0.9-3.0.11  ⇒ 3.0.11  
3.0.12-master  ⇒ master

2016-11-15 08:23 UTC, ryo-endo requested changes
- [ ] CovallasとSensioLabs解析の対応をお願いします。

2016-11-15 08:36 UTC, ryo-endo commented on .travis.yml
> +  matrix:
3.0.0-3.0.8は、プラグインのUnitTestが技術的にできない。

2016-11-15 08:37 UTC, ryo-endo commented on .travis.yml
> +  matrix:
いまのままにする。

2016-11-17 05:19 UTC, ryo-endo requested changes

2016-11-17 05:19 UTC, ryo-endo commented on Event.php
> +        if (Version::isSupportGetInstanceFunction()) {
- [ ] ここは`isSupportNewHookpoint`が意味的に正しい。

2016-11-17 05:19 UTC, ryo-endo commented on Event.php
> +        if (Version::isSupportGetInstanceFunction()) {
- [ ] ここは`isSupportNewHookpoint`が意味的に正しい。

2016-11-17 05:19 UTC, ryo-endo commented on README.md
> +[![Build Status](https://travis-ci.org/eccubevn/related-product-plugin.svg?branch=related-renew)](https://travis-ci.org/eccubevn/related-product-plugin)
- [ ] eccubevnはNG

2016-11-17 05:19 UTC, ryo-endo commented on README.md
> +[![Build status](https://ci.appveyor.com/api/projects/status/pwl6k02to4v2x681/branch/related-renew?svg=true)](https://ci.appveyor.com/project/lammn/related-product-plugin/branch/related-renew)
- [ ] lammnはNG

2016-11-17 05:19 UTC, ryo-endo commented on README.md
> +[![Coverage Status](https://coveralls.io/repos/github/eccubevn/maker-plugin/badge.svg?branch=maker-renew)](https://coveralls.io/github/eccubevn/maker-plugin?branch=maker-renew)
- [ ] eccubevnはNG

2016-11-17 05:19 UTC, ryo-endo commented on Utils/Version.php
> + * This file is part of the Recommend plugin
- [ ] Recommend ⇒ Related Product

2016-11-17 05:27 UTC, ryo-endo requested changes

2016-11-17 05:27 UTC, ryo-endo commented on Event/EventLegacy.php
> +            if ($form->isValid()) {
- [ ] https://github.com/EC-CUBE/related-product-plugin/issues/27 の対応です。
```
$form['related_collection']->isValid()
```
に変更お願いします。

2016-11-17 05:58 UTC, lammn commented on README.md
> +[![Build status](https://ci.appveyor.com/api/projects/status/pwl6k02to4v2x681/branch/related-renew?svg=true)](https://ci.appveyor.com/project/lammn/related-product-plugin/branch/related-renew)
What account is ok?

2016-11-17 05:58 UTC, lammn commented on README.md
> +[![Build Status](https://travis-ci.org/eccubevn/related-product-plugin.svg?branch=related-renew)](https://travis-ci.org/eccubevn/related-product-plugin)
What account is ok?

2016-11-17 09:30 UTC, closed without merging